Home end point
fack2/Artists8 pull request #9
Opened 2019-08-06 13:14 UTC by YousefQwasmeh

2019-08-06 13:25 UTC, jema28 requested changes

2019-08-06 13:25 UTC, jema28 commented on config.env
> +DATABASE_URL = postgres://yizthhwjzzmgrm:8d830f4e30e56aedc270b92fe7fdf98d083113b2169c99394e52d4a17ba4a808@ec2-50-19-222-129.compute-1.amazonaws.com:5432/d9bltlsuv2jqs
You shouldn't have your config.env up on github, please add this to your .gitignore.

2019-08-06 13:25 UTC, jema28 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
Please delete this as not being used.

2019-08-06 13:25 UTC, jema28 commented on src/app.js
> +    // partialsDir: path.join(__dirname, "views", "partials")
Why did you comment this out?

2019-08-06 13:25 UTC, jema28 commented on src/app.js
> +app.get("/", (req, res,next) => {
This method should be in a controller. Then write the method in the router index.js controller folders.

2019-08-06 13:25 UTC, jema28 commented on src/app.js
> +      next(err);
Where are you handling this? This will break if you don't have a global error middleware.

2019-08-06 13:25 UTC, jema28 commented on src/app.js
> +      console.log(data,"00000000")
Please delete this console.log.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +BEGIN;
Please check this file in prettier.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +    name VARCHAR(150) NOT NULL,
Should this be unique?

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +    coutry VARCHAR(40)
Spelling mistake: 'country'.

2019-08-06 13:25 UTC, jema28 commented on src/app.js
> +  get4painting((err,data)=>{
This should be called getExpensivePaintings.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +CREATE TABLE paintaings (
Spelling error: 'paintings'.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +INSERT INTO paintaings (name, price, discription,img, id_artist ) VALUES
Same error.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +    discription text ,
Spelling error: 'description'.

2019-08-06 13:25 UTC, jema28 commented on src/database/db_build.sql
> +INSERT INTO paintaings (name, price, discription,img, id_artist ) VALUES
Same error here also.

2019-08-06 13:28 UTC, jema28 requested changes

2019-08-06 13:28 UTC, jema28 commented on src/database/db_build.sql
> +INSERT INTO paintaings (name, price, discription,img, id_artist ) VALUES
Please look at the spacing here: your commas aren't in the right place.

2019-08-06 13:28 UTC, jema28 commented on src/queries/getData.js
> +    `select id,name,price,img from paintaings order By price desc limit 4;`,
Keep consistent here e.g. if you're using lowercase please write 'by'. You should also add spaces between the inputs e.g id, name, price

2019-08-06 13:28 UTC, jema28 commented on src/views/home.hbs
> +
Please delete this space.

2019-08-06 13:28 UTC, jema28 commented on src/views/home.hbs
> +<h2>the most expensive 4 paintings</h2>
'The four most expensive paintings'

2019-08-06 13:28 UTC, jema28 commented on src/views/layouts/main.hbs
> +  <!-- //web font -->
Please delete.

2019-08-06 13:28 UTC, jema28 commented on src/views/layouts/main.hbs
> +<!DOCTYPE html>
Is this eslinted?

2019-08-06 13:28 UTC, jema28 commented on src/views/home.hbs
> +        <div>
You could change this to an article tag.

2019-08-06 19:43 UTC, 95Rawan commented on src/database/db_build.sql
> +INSERT INTO artists (id, name, coutry) VALUES
Why are you adding the id manually?

2019-08-06 19:44 UTC, 95Rawan commented on src/database/db_build.sql
> +INSERT INTO paintings (name, price, description, img, id_artist) VALUES
the id is manually added here too

2019-08-07 05:41 UTC, jema28 requested changes

2019-08-07 05:41 UTC, jema28 commented on config.env
> +DATABASE_URL = postgres://yizthhwjzzmgrm:8d830f4e30e56aedc270b92fe7fdf98d083113b2169c99394e52d4a17ba4a808@ec2-50-19-222-129.compute-1.amazonaws.com:5432/d9bltlsuv2jqs
Please remove this file from the cache.

2019-08-07 05:55 UTC, jema28 requested changes

2019-08-07 05:55 UTC, jema28 commented on package.json
> +  "dependencies": {
Where are express and express-handlebars? These need to be added.

2019-08-07 05:55 UTC, jema28 commented on src/controllers/home.js
> +module.exports.get=("/", (req, res,next) => {
This should be `exports.get`.

2019-08-07 05:55 UTC, jema28 commented on src/controllers/index.js
> +router.use(express.json());
Please add space here.

2019-08-07 05:55 UTC, jema28 commented on src/database/db_build.js
> +const fs = require("fs");
Please sort out your eslint!!!

2019-08-07 06:00 UTC, jema28 requested changes

2019-08-07 06:00 UTC, jema28 commented on src/app.js
> +const router = require('./controllers/index');
You don't need index here.

2019-08-07 06:00 UTC, jema28 commented on src/app.js
>  const exphbas = require("express-handlebars");
Spelling error here: 'exphbs'. Please change this in line 15 also.

2019-08-07 06:00 UTC, jema28 commented on package.json
> +  "dependencies": {
I think this is a problem with your version of node/npm, you may have to update them.

2019-08-07 07:21 UTC, jema28 approved these changes

2019-08-07 07:21 UTC, merged